print ("This program will calculate the sum, product difference, quotient and remainder of two inputted numbers. ")
print ("Enter the two numbers.\n")
x = int(input ())
y = int(input ())
print ("Sum = " + str(x + y))
print ("Product = " + str(x*y))
print ("Difference = " + str(x-y))
print ("Quotient = " + str(x//y))
print ("Remainder of division = " + str(x%y))
